[2024-05-25T21:58:54.267+0000] {task_context_logger.py:104} WARNING - Marking task instance <TaskInstance: process_sales.read_send_data_task scheduled__2022-12-24T01:00:00+00:00 [queued]> stuck in queued as failed. If the task instance has available retries, it will be retried.
