[2024-05-27T20:17:00.386+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-27T20:17:00.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales.get_send_data_task manual__2024-05-27T20:16:57.869708+00:00 [queued]>
[2024-05-27T20:17:00.435+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales.get_send_data_task manual__2024-05-27T20:16:57.869708+00:00 [queued]>
[2024-05-27T20:17:00.436+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-27T20:17:00.455+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_send_data_task> on 2024-05-27 20:16:57.869708+00:00
[2024-05-27T20:17:00.461+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4920) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-27T20:17:00.464+0000] {standard_task_runner.py:63} INFO - Started process 4922 to run task
[2024-05-27T20:17:00.464+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales', 'get_send_data_task', 'manual__2024-05-27T20:16:57.869708+00:00', '--job-id', '2448', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmpjh7gp_jf']
[2024-05-27T20:17:00.468+0000] {standard_task_runner.py:91} INFO - Job 2448: Subtask get_send_data_task
[2024-05-27T20:17:00.531+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales.get_send_data_task manual__2024-05-27T20:16:57.869708+00:00 [running]> on host 6ecac41592ab
[2024-05-27T20:17:00.652+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gurlenko.1488@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales' AIRFLOW_CTX_TASK_ID='get_send_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-27T20:16:57.869708+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-27T20:16:57.869708+00:00'
[2024-05-27T20:17:00.655+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-27T20:17:00.656+0000] {logging_mixin.py:188} INFO - Starting job 1
[2024-05-27T20:17:01.056+0000] {logging_mixin.py:188} INFO - Passion
[2024-05-27T20:17:01.057+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-27T20:17:01.058+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-27T20:17:01.070+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=process_sales, task_id=get_send_data_task, run_id=manual__2024-05-27T20:16:57.869708+00:00, execution_date=20240527T201657, start_date=20240527T201700, end_date=20240527T201701
[2024-05-27T20:17:01.097+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-27T20:17:01.122+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-27T20:17:01.123+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
